import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Form from '../components/Form'

const Home: NextPage = () => {
  return (
    <div className={styles.content}>
      <Head>
        <title>Blockchain App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <div className={styles.containerNavbar}>
          <Link href="/">Asaiah Henson</Link>
          <ConnectButton />
        </div>
        <div className={styles.container}>

        <Form />
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" className={styles.footer} rel="noopener noreferrer" target="_blank">
          Created By DreamerWebdev
        </a>
      </footer>
    </div>
  );
};

export default Home;
